### ISSUE TITLE
Crash when creating csv file

### ISSUE THREAD

**Issue by Leniff** [Neotys-Labs/neoload-cli#174]
Since the upgrade from version 1.2.1 to 1.3.3 I can no longer create a csv file
See stack trace:

C:\Users\droussel>neoload report --template builtin:transactions-csv > temp.csv
Traceback (most recent call last):
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\droussel\AppData\Local\Programs\Python\Python39\Scripts\neoload.exe\__main__.py", line 7, in <module>

  File "c:\users\droussel\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\site-packages\neoload\commands\report.py", line 68, in cli
    model = initialize_model(filter, template)
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\site-packages\neoload\commands\report.py", line 128, in initialize_model
    parse_template_spec(model,filter_spec,template.strip())
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\site-packages\neoload\commands\report.py", line 180, in parse_template_spec
    model["template_text"] = get_builtin_template_transaction_csv()
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\site-packages\neoload\commands\report.py", line 1033, in get_builtin_template_transaction_csv
    return get_resource_as_string('tests/resources/jinja/builtin_transactions_csv.j2').strip()
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\site-packages\neoload\commands\report.py", line 173, in get_resource_as_string
    return pkg_resources.read_text(namespace, file)
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\importlib\resources.py", line 139, in read_text
    with open_text(package, resource, encoding, errors) as fp:
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\importlib\resources.py", line 121, in open_text
    open_binary(package, resource), encoding=encoding, errors=errors)
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\importlib\resources.py", line 87, in open_binary
    resource = _normalize_path(resource)
  File "c:\users\droussel\appdata\local\programs\python\python39\lib\importlib\resources.py", line 62, in _normalize_path
    raise ValueError('{!r} must be only a file name'.format(path))
ValueError: 'tests/resources/jinja/builtin_transactions_csv.j2' must be only a file name
###

**Comment by paulsbruce** [comment]
@Leniff a patch has been issued on the branch FixWinResourcePaths. While we are packaging/releasing the next version soon, can you try this branch on your own environment by using:

pip install git+https://github.com/Neotys-Labs/neoload-cli.git@FixWinResourcePaths

...instead of the usual pip install neoload for the short-term? Once you confirm that it's working for you, we will circle back on and close this issue once an official patch is released via Pypi.

**Comment by Leniff** [comment]
Thanks for your quick reply, the patch is working, I have no more errors, the file is created successfully.
