### ISSUE TITLE
How to configure "local docker infrastructure"

### ISSUE THREAD

**Issue by chiabre** [Neotys-Labs/neoload-cli#183]
Hello,
the doc reports the config options and default values but it's not clear how/where to customize the conf itself.

I tried to add the conf to

` /home/ubuntu/.local/share/neoload-cli/1.0/config-global.yaml`

in yaml format but it didn't work. The only format that seems to work is
```
docker.zone:
- eTkFb
docker.lg.default_count: 1

```
but it gives the following error
```
neoload docker status
configuration:
docker.controller.image = neotys/neoload-controller:latest
docker.controller.default_count = 1
docker.lg.image = neotys/neoload-loadgenerator:latest
docker.lg.default_count = 1
docker.zone = ['eTkFb']
docker.launched = []

docker hooks is installed

image neotys/neoload-loadgenerator:latest is pulled
image neotys/neoload-controller:latest is pulled
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/neoload", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/neoload/commands/docker.py", line 38, in cli
    docker_lib.status()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/neoload/neoload_cli_lib/docker_lib.py", line 87, in status
    check_zone(get_setting(DOCKER_ZONE))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/neoload/neoload_cli_lib/docker_lib.py", line 121, in check_zone
    raise cli_exception.CliException("zone " + zone_set + " doesn't exist")
TypeError: can only concatenate str (not "list") to str
```

**Comment by guillaumebert** [comment]
Indeed, the documentation does not explain how to set the docker configuration.
You can do that using the config command, do not edit the `config-global.yaml` file manually. Example: `neoload config set docker.zone=eTkFb`
The docker zone cannot be a list, this is only the ID of one zone.
