### ISSUE TITLE
An unexpected error occurred during test run

### ISSUE THREAD

**Issue by matewoj** [Neotys-Labs/neoload-cli#193]
Hello,

I'd like to run test.yaml as a code and I get below error during test execution.
When I run the same test from GUI instead of NeoloadCLI it works.

`
neoload run --as-code test.yaml --name TestCLI
`

Do I missed something when using NeoloadCLI ?

Regards
Mateusz

Starting dynamic infrastructure...
--
Infrastructure starting: 10%
Infrastructure starting: 20%
Infrastructure starting: 20%
Infrastructure starting: 20%
Infrastructure starting: 20%
Infrastructure starting: 20%
Infrastructure starting: 35%
Infrastructure starting: 52%
Infrastructure starting: 52%
Infrastructure starting: 52%
Infrastructure starting: 54%
Infrastructure starting: 62%
Infrastructure starting: 68%
Infrastructure starting: 68%
Infrastructure starting: 72%
Infrastructure starting: 72%
Infrastructure starting: 72%
Infrastructure starting: 83%
Infrastructure starting: 83%
Infrastructure starting: 85%
Infrastructure starting: 86%
Infrastructure starting: 86%
Infrastructure starting: 97%
Dynamic infrastructure started.
Controller preparation
Lock controller nlca-prod-c15fb641-5b7c-4204-8cc0-2cdc3f717c8c-4741-0-vm
Waiting lock for controller nlca-prod-c15fb641-5b7c-4204-8cc0-2cdc3f717c8c-4741-0-vm (0/8)
Load generators preparation
Lock load generators : nllga-prod-c15fb641-5b7c-4204-8cc0-2cdc3f717c8c-4742-0-vm
Waiting lock for load generators nllga-prod-c15fb641-5b7c-4204-8cc0-2cdc3f717c8c-4742-0-vm (0/8)
Sending project to controller
Sending load generators details to controller
Sending additional as-code file
Starting infrastructure and test
 
 
An unexpected error occurred
Unlocking controller : nlca-prod-c15fb641-5b7c-4204-8cc0-2cdc3f717c8c-4741-0-vm
Unlocking load generator : nllga-prod-c15fb641-5b7c-4204-8cc0-2cdc3f717c8c-4742-0-vm
java.lang.IllegalStateException: controller exited unexpectedly
at com.neotys.nlweb.bench.runtime.service.task.start.StartBenchCheckingTask.lambda$doExecution$0(StartBenchCheckingTask.java:63)
at rx.internal.operators.CompletableFlatMapSingleToCompletable$SourceSubscriber.onSuccess(CompletableFlatMapSingleToCompletable.java:61)
at rx.Single$18.onNext(Single.java:1911)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
at rx.Single$1$1.onSuccess(Single.java:80)
at rx.internal.operators.SingleOperatorOnErrorResumeNext$2.onSuccess(SingleOperatorOnErrorResumeNext.java:63)
at rx.Single$18.onNext(Single.java:1911)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)

**Comment by guillaumebert** [comment]
Hello,
I think that this error is not related to NeoLoad CLI. To investigate, you should look at NeoLoad controller logs.
But this github repository is not the right place for support, I invite you to create a support case [here](https://www.neotys.com/accountarea/casecreate.php). 
Thank you
